application: higashi-dance-network
version: 1
runtime: python
api_version: 1

default_expiration: "1m"

handlers:

- url: /favicon.ico
  static_files: public/favicon.ico
  upload: public/favicon.ico
  mime_type: image/x-icon

- url: /proxy/.*
  script: proxy/proxy.py

- url: /kasanegi
  script: fallback.py

- url: /iromiru
  script: fallback.py

- url: /bon2/
  script: fallback.py

- url: /data/.*
  script: data.py

- url: (.*)/
  static_files: public\1/index.html
  upload: public(.*)/index.html

- url: /hanabi/uchiage/.*
  static_files: public/hanabi/uchiage/index.html
  upload: public/hanabi/uchiage/index.html

- url: /(.*)
  static_files: public/\1
  upload: public/(.*)
